# -*- coding: utf-8 -*-
"""_01_integer_assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTNsIVVqnXgxIM5vJ64zacc-_TMQq6US
"""

# Question 1: Calculate the product of first 10 natural numbers
n=10
product=1
for i in range(n):
  product=product*(i+1)
print(product)

# Question 2: Find the remainder when 156 is divided by 7
number=156
remainder=number%7
print(remainder)

# Question 3: Calculate the square of 25
number=5
square=number**2
print(square)

# Question 4:  Find the cube root of 125
number=125
cube_root=number**(1/3)
print(cube_root)

# Question 5: Calculate the sum of digits in number 12345
number=12345
sum_of_digit =0
for i in range(number):
  sum_of_digit=sum_of_digit+number%10
  number=number//10
print(sum_of_digit)

# Question 6: Check if 97 is a prime number
number=97
for i in range(number,number+1):
  if number%i==0:
    print(number,"is not a prime number")
    # break
  else:
    print(number,"is a prime number")
    # break

# Question 7: Find the factorial of 8
factorial_count=1
for i in range(1,9) :
  factorial_count=factorial_count*i

print(factorial_count)

#  Calculate the average of numbers: 15, 23, 31, 42, 56
numbers=[15,23,31,42,56]
average_of_numbers=sum(numbers)/len(numbers)
print(average_of_numbers)
# len(numbers)
# sum(numbers)

# Find the greatest common divisor (GCD) of 48 and 36
a=48
b=36
common_factors=[]
for i in range(1,min(a,b)+1):
  if a%i==0 and b%i==0:
    common_factors.append(i)
print(max(common_factors))

1,2,3,4,6,8,12,16,24,48

print(number_1_factors)
print(number_2_factors)

# # Find the greatest common divisor (GCD) of 48 and 36
number_1 = 48
number_2 = 36

number_1_factors = []
number_2_factors = []
common_factors = []

for i in range(1, number_1 + 1):
    if number_1 % i == 0:
        number_1_factors.append(i)
print(number_1_factors)

for i in range(1, number_2 + 1):
    if number_2 % i == 0:
        number_2_factors.append(i)
print(number_2_factors)

for factor in number_1_factors:
    if factor in number_2_factors:
        common_factors.append(factor)

print(common_factors)
print(max(common_factors))

# calculate the sum of first 20 odd numbers
odd_sum=0
for i in range(1,40):
  # print(i%2!=0)
  if i%2!=0:
    odd_sum=odd_sum+i
print(odd_sum)



