# -*- coding: utf-8 -*-
"""_02_Float_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMbRLdftAV5-1G3sWOaX6pQUCagYupXE
"""

# Question 1: Calculate the average of 3.14, 2.718, 1.618, 0.577
numbers=[3.14, 2.718, 1.618, 0.577]
average_of_numbers=sum(numbers)/len(numbers)
print(average_of_numbers)

# Question 2: Convert 98.6 Fahrenheit to Celsius (F = C * 9/5 + 32)
fahrenheit=98.6
celsius=fahrenheit-32
celsius=celsius*5/9
print(celsius)



#  Question 3: Calculate the compound interest on $1000 at 5.5% for 3 years
total=1000
rate=0.055
time=3
compound_interest=total*(1+rate)**time
print(compound_interest)

# Question 4: Find the hypotenuse of a right triangle with sides 3.5 and 4.2
a=3.5
b=4.2

hypotenuse = (a**2 + b**2) ** (1/2)

print(hypotenuse)

#  Question 5: Calculate the volume of a sphere with radius 7.8

r = 7.8
volume = (4/3) * 3.14* r**3
print(volume)



# Question 6: Round 3.14159 to 3 decimal places
number=3.14159
round(number,3)

# Question 7: Calculate the percentage: 45 out of 67
percentage=(45/67)*100
print(percentage)

# Question 8: Find the square root of 23.456
number=23.456
square_root=number**(1/2)
print(square_root)

#  Question 9: Calculate the simple interest: Principal=2500, Rate=6.5%, Time=2.5 years
principal=2500
rate=0.65
time=2.5
simple_interset=principal*rate*time
print(simple_interset)

# Question 10: Convert 45.7 degrees to radians

degrees=45.7
radians=degrees*3.14/180
print(radians)