# -*- coding: utf-8 -*-
"""_03_strings_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNHixDRh0TTTRuco0Y8hH6duMW-CQ1-F
"""

# Question 1: Reverse the string "Python Programming"
text="Python Programming"
text[::-1]

# Question 2: Check if "racecar" is a palindrome
text="racecar"
if text[::-1]==text[0::]:
  print(f"{text} is a palindrome")
else:
  print(f"{text} is not a palindrome")

# Question 3: Count the number of words in "Python is a great programming language"
text="Python is a great programming language"
len(text.split())

# Convert "hello world" to title case
text="hello world"
text.title()

# # Question 5: Find the length of string "Data Science"
text="Data Science"
len(text)

# Question 6: Replace all spaces with underscores in "Machine Learning"
text="Machine Learning"
text=text.replace(" ","_")
print(text)

# Question 7: Check if "python" is in "Python Programming Language"
text ="Python Programming Language"
if "Python" in text:
  print("python is in the text")
else:
  print("python is not in the text")

# Question 8: Extract the first 5 characters from "Artificial Intelligence"
text="Artificial Intelligence"
text[0:5]

# Question 9: Convert "UPPERCASE" to lowercase
text="Prasanna"
text.lower()

# Question 10: Remove all vowels from "Computer Science"
text = "Computer Science"

result = ""

vowels = ['A','E','I','O','U','a','e','i','o','u']

for i in text:
    if i not in vowels:
        result = result + i

print(result)

# Question 11: Find the most frequent character in "mississippi"
text="mississippi"
letter_count=0
letter=''
for i in text:
  if text.count(i)>letter_count:
    letter=i
    letter_count=text.count(i)
print(f"{letter} : {letter_count}")

# Question 12: Check if two strings are anagrams: "listen" and "silent"
text1="listen"
text2="silent"
if sorted(text1)==sorted(text2):
  print(f"{text1} and {text2} are anagrams")
else:
  print(f"{text1} and {text2} are not anagrams")

# Question 13: Capitalize first letter of each word in "python programming language"
text="python programming language"
text.title()

# Question 14: Count consonants in "Hello World"
text="Hello World"
vowels = ['A','E','I','O','U','a','e','i','o','u']
result=''

for i in text:
    if i not in vowels:
        result = result + i
        count=len(result)
print(count)


print(result)

# Question 15: Find the longest word in "Python is a programming language"
text="Python is a programming language"
longest_word_count=text.split()
longest_word_count
word_count=len(longest_word_count[0])
for i in longest_word_count:
  if len(i)>word_count:
    word_count=len(i)
    print(f"word_count: {word_count}")
    print(f"i: {i}")

# Question 15: Find the longest word in "Python is a programming language"
text="Python is a programming language"
longest_word_count=text.split()
longest=''
for i in longest_word_count:
  if len(i)>len(longest):
    # pass
    longest=i
print(longest)

# Question 16: Remove all punctuation from "Hello, World! How are you?"
text="Hello, World! How are you?"
for i in string.punctuation: #punctuation removes alla punctuation from the string
  pass
  text=text.replace(i,"")
print(text)

# Question 17: Check if string starts with "Python"
text="Python"
if text.startswith('P'):
  print(f"{text} starts with p")
else:
  print(f"{text} does not start with p")

# Question 18: Find the index of first occurrence of 'o' in "Hello World"
text="Hello World"
text.find('o')

# Question 19: Split string "apple,banana,orange" by comma
text="apple,banana,orange"
text.split(',')

# Question 20: Join list ['Python', 'is', 'awesome'] with spaces
text=['Python', 'is', 'awesome']
updated_text=" ".join(text)
print(updated_text)

# Question 21: Check if string contains only digits: "12345"
text="12345"
if text.isdigit():
  print(f"{text} contains only digits")
else:
  print(f"{text} does not contains only digits")

# Question 22: Check if string contains only letters: "HelloWorld"
text="HelloWorld"
if text.isalpha():
  print(f"text contains only letters")
else:
  print(f"text does not contains only letters")

# Question 23: Convert "hello world" to "hElLo WoRlD" (alternating case)
text="hello world"
updated_text=""
for i in range(len(text)):
  pass
  if i % 2 == 0:
    print(text[i].upper(),end="")
  else:
    print(text[i].lower(),end="")

# Question 24: Find all positions of 'a' in "banana"
text="banana"
count_position=0
for i in range(len(text)):
  if text[i]=='a':
    count_position+=1
    print(i)
# print(count_position)

# Question 25: Remove leading and trailing whitespace from "  Hello World  "
text="  Hello World  "
text.strip()

# Question 26: Check if string ends with "ing": "programming"
text="programming"
text.endswith('ing')

# Question 27: Replace first occurrence of 'o' with '0' in "Hello World"
text="Hello World"
text.replace('o','0',1)

# Question 28: Find the shortest word in "Python is a programming language"
text="Python is a programming language"
longest_word_count=text.split()
longest_word_count
word_count=len(longest_word_count[0])
for i in longest_word_count:
  if len(i)<word_count:
    word_count=len(i)
    print(f"word_count: {word_count} ,word is {i}")
    # print(f" {i}")

# Question 29: Count words that start with 'p' in "Python programming is powerful"
text="Python programming is powerful"
text.startswith('p')

# Question 30: Reverse words in "Hello World Python"
text="Hello World Python"
text.split()[::-1]
# text[::-1]

# Question 31: Check if string is a valid email format: "user@example.com"

# Question 32: Extract domain from "https://www.example.com/path"

# Question 33: Count lines in multi-line string

# Question 34: Find common characters between "hello" and "world"
text_1="hello"
text_2="world"
for i in text_1 and text_2:
  if i in text_1 and text_2:
    print(i)

# Question 35: Check if string is a valid phone number: "+1-555-123-4567"

# Question 36: Extract numbers from "abc123def456ghi789"
text="abc123def456ghi789"
for i in text:
  if i.isdigit():
    print(i,end="")

# Question 37: Convert "snake_case" to "camelCase"
text="pyhton_programming"
text.title().replace("_","")

# Question 38: Check if string is a valid palindrome ignoring case: "A man a plan a canal Panama"
text="A man a plan a canal Panama"
updated_text.replace(" ","")
# print(updated_text)
updated_text=updated_text.lower()
# print(updated_text)
if updated_text[::-1]==updated_text[0::]:
  print(f"{updated_text} is a palindrome")
else:
  print(f"{updated_text} is not a palindrome")

# Question 39: Find the most common word in "the quick brown fox jumps over the lazy dog"

# Question 40: Generate acronym from "National Aeronautics And Space Administration"
text="National Aeronautics And Space Administration"
text.split()
for i in text.split():
  print(i[0],end="")

# Question 41: Check if string contains balanced parentheses: "((()))"
text="((()))"
if text.count('(')==text.count(')'):
  print(f"{text} contains balanced parentheses")
else:
  print(f"{text} does not contains balanced parentheses")

# Question 42: Convert "hello world" to Morse code

# Question 43: Find the longest common substring between "programming" and "grammar"

# Question 44: Check if string is a valid URL: "https://www.google.com"

#  Question 45: Extract all words with length > 5 from "Python programming is amazing and powerful"
text="Python programming is amazing and powerful"
for i in text.split():
  if len(i)>5:
    print(i)

# Question 46: Convert "hello world" to Pig Latin

# Question 47: Check if string is a valid IPv4 address: "192.168.1.1"

# Question 48: Find all substrings of "abc"

# Question 49: Convert "hello world" to ROT13 encoding

# Question 50: Check if string is a valid credit card number: "4532015112830366"