# -*- coding: utf-8 -*-
"""Boolean_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkVUbQViAJL0cMqK2e-yqdZFcQt79J0a
"""

# Question 1: Check if 25 is greater than 20 and less than 30
number_1 = 25
number_2 = 20
number_3 = 30
if number_1 > number_2 and number_1 < number_3:
    print("True")
else:
    print("False")

# Question 2: Check if string "python" is equal to "Python" (case sensitive)
string_1 = "python"
string_2 = "Python"
if string_1 == string_2:
    print("True")
else:
    print("False")

# Question 3: Check if 15 is divisible by both 3 and 5
number = 15
if number % 3 == 0 and number % 5 == 0:
    print("True")
else:
    print("False")

# Question 4: Check if 7 is not equal to 8
number_1 = 7
number_2 = 8
if number_1 != number_2:
    print("True")
else:
    print("False")

# Question 5: Check if 100 is greater than 50 or less than 25
number_1 = 100
number_2 = 50
number_3 = 25
if number_1 > number_2 or number_1 < number_3:
    print("True")
else:
    print("False")

# Question 6: Check if 0 is falsy in Python
number = 0
if number:
    print("True")
else:
    print("False")

# Question 7: Check if empty string "" is falsy in Python
txt = ""
if txt:
    print("True")
else:
    print("False")

# Question 8: Check if 42 is truthy in Python
number = 42
if number:
    print("True")
else:
    print("False")

# Question 9: Check if 10 is between 5 and 15 (inclusive)
number_1 = 10
number_2 = 5
number_3 = 15
if number_2 <= number_1 <= number_3: # between <=
    print("True")
else:
    print("False")

# Question 10: Check if 3.14 is greater than 3 and less than 4
number_1 = 3.14
number_2 = 3
number_3 = 4
if number_2 < number_1 < number_3:     #
    print("True")
else:
    print("False")