# -*- coding: utf-8 -*-
"""Complex_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q57GYVGJCnRijo6s3kgw1RN6St0e6iaF
"""

# Question 1: Create complex number 5 + 3j
com_num = 5 + 3j
print(com_num)

# Question 2: Find the real part of complex number 7 - 2j
com_num = 7 - 2j
print(com_num.real)

# Question 3: Find the imaginary part of complex number 4 + 6j
com_num = 4 + 6j
print(com_num.imag)

# Question 4: Add two complex numbers: (3 + 2j) and (1 + 4j)
com_num1 = 3 + 2j
com_num2 = 1 + 4j
print(com_num1 + com_num2)

#  Question 5: Multiply two complex numbers: (2 + 3j) and (1 + 2j)
com_num1 = 2 + 3j
com_num2 = 1 + 2j
print(com_num1 * com_num2)

# Question 6: Find the magnitude of complex number 6 + 8j
com_num = 6 + 8j
print(abs(com_num))    #absolute value

# Question 7: Find the conjugate of complex number 5 - 7j
com_num = 5 - 7j
print(com_num.conjugate())  # keep the real part same and  change the sign of the imaginary part

# Question 8: Subtract complex numbers: (10 + 5j) - (3 + 2j)
com_num1 = 10 + 5j
com_num2 = 3 + 2j
print(com_num1 - com_num2)

# Question 9: Divide complex numbers: (8 + 6j) / (2 + 1j)
com_num1 = 8 + 6j
com_num2 = 2 + 1j
print(com_num1 / com_num2)

# Question 10: Find the phase angle of complex number 1 + 1j
com_number=1+1j
print(cmath.phase(com_number))
# cmath --------> complex math  cmath.phase finds angle of complex number

