# -*- coding: utf-8 -*-
"""dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lq15QksyNHMJMtfcdcRPPtJY_3Ea2ZYV
"""

# Question 1: Create a dictionary of student names and their ages
elements={'prasanna':21,'ram':23,'bhavana':21}
elements

# Question 2: Add a new key-value pair to dictionary {'a': 1, 'b': 2, 'c': 3}
dict_values={'a': 1, 'b': 2, 'c': 3}
dict_values['d']=4
dict_values

# Question 3: Get all keys from dictionary {'name': 'John', 'age': 25, 'city': 'New York'}
dict_values={'name': 'John', 'age': 25, 'city': 'New York'}
dict_values.keys()

# Question 4: Get all values from dictionary {'python': 3, 'java': 2, 'c++': 1}
dict_valuse={'python': 3, 'java': 2, 'c++': 1}
dict_valuse.values()

# Question 5: Check if key 'age' exists in {'name': 'Alice', 'age': 30, 'city': 'London'}
dict_values={'name': 'Alice', 'age': 30, 'city': 'London'}
if 'age' in dict_values:
  print('age exists')
else:
  print('age does not exists')

# Question 6: Remove key 'temp' from {'a': 1, 'b': 2, 'temp': 3, 'c': 4}
dict_values={'a': 1, 'b': 2, 'temp': 3, 'c': 4}
del dict_values['temp']
dict_values

# Question 7: Find the sum of all values in {'math': 85, 'science': 92, 'english': 78}
dict_values={'math': 85, 'science': 92, 'english': 78}
sum(dict_values.values())

# Question 8: Create a dictionary with squares of numbers 1 to 5
dict_values={}
for i in range(1,6):
  dict_values[i]=i**2
dict_values

# Question 9: Count frequency of each character in string "hello"
string='hello'
dict_values={}
for i in string:
  if i in dict_values:
    dict_values[i]+=1
  else:
    dict_values[i]=1
dict_values

# Question 10: Merge two dictionaries {'a': 1, 'b': 2} and {'c': 3, 'd': 4}
dict_values1={'a': 1, 'b': 2}
dict_values2={'c': 3, 'd': 4}
dict_values1.update(dict_values2)
dict_values1

# Question 11: Create a nested dictionary: {'person': {'name': 'Alice', 'age': 25}}
dict_values={'person': {'name': 'Alice', 'age': 25}}
dict_values

# Question 12: Access nested value 'name' from {'person': {'name': 'Alice', 'age': 25}}
dict_values={'person': {'name': 'Alice', 'age': 25}}
dict_values['person']['name']

# Question 13: Create a dictionary with list values: {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
dict_values={'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
dict_values

# Question 14: Add 'orange' to the 'fruits' list in nested dictionary
dict_values={'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
dict_values['fruits'].append('orange')
dict_values

# Question 15: Create a dictionary with tuple values: {'coordinates': (10, 20), 'rgb': (255, 0, 0)}
dict_values={'coordinates': (10, 20), 'rgb': (255, 0, 0)}
dict_values

# Question 16: Extract first coordinate from nested tuple
dict_values={'coordinates': (10, 20), 'rgb': (255, 0, 0)}
dict_values['coordinates'][0]

# Question 17: Create a dictionary with set values: {'vowels': {'a', 'e', 'i'}, 'consonants': {'b', 'c', 'd'}}
dict_values={'vowels': {'a', 'e', 'i'}, 'consonants': {'b', 'c', 'd'}}
dict_values

# Question 18: Add 'o' to vowels set in nested dictionary
dict_values={'vowels': {'a', 'e', 'i'}, 'consonants': {'b', 'c', 'd'}}
dict_values['vowels'].add('o')
dict_values

# Question 19: Create a 3-level nested dictionary: {'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}
dict_values={'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}
dict_values

# Question 20: Access employee name from 3-level nested dictionary
dict_values={'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}
dict_values['company']['department']['employee']['name']

# Question 21: Create a dictionary with mixed data types: {'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}
dict_values={'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}
dict_values

# Question 22: Check data type of each value in mixed dictionary
dict_values={'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}
a=dict_values.values()
for i in a:
  print(type(i))
# dict_values

# Question 23: Create a dictionary with function values: {'len': len, 'str': str, 'int': int}
dict_values={'len': len, 'str': str, 'int': int}
dict_values

# Question 24: Apply each function to "123" using dictionary
dict_values={'len': len, 'str': str, 'int': int}
for i in dict_values.values():
  print(i('123'))

# Question 25: Create a dictionary with lambda functions: {'double': lambda x: x*2, 'square': lambda x: x**2}
dict_values={'double': lambda x: x*2, 'square': lambda x: x**2}
dict_values

# Question 26: Apply each lambda function to 5
dict_values={'double': lambda x: x*2, 'square': lambda x: x**2}
for i in dict_values.values():
  print(i(5))

# Question 27: Create a dictionary with class values: {'list': list, 'dict': dict, 'set': set}
dict_values={'list': list, 'dict': dict, 'set': set}
dict_values

# Question 28: Create instances using class dictionary
dict_values={'list': list, 'dict': dict, 'set': set}
lst=dict_values['list']()
dct=dict_values['dict']()
st=dict_values['set']()
print(lst)
print(dct)
print(st)

dict_values={'list': list, 'dict': dict, 'set': set}
for i in dict_values.values():
  print(i())

# Question 29: Create a dictionary with None values: {'a': None, 'b': None, 'c': None}
dict_values={'a': None, 'b': None, 'c': None}
dict_values

# Question 30: Replace all None values with 0
dict_values={'a': None, 'b': None, 'c': None}
dict_values['a']=0
dict_values['b']=0
dict_values['c']=0

# Question 30: Replace all None values with 0
dict_values={'a': None, 'b': None, 'c': None}
for i in dict_values.keys():
  dict_values[i]=0
dict_values

# Question 31: Create a dictionary with boolean values: {'is_active': True, 'is_admin': False}
dict_values={'is_active': True, 'is_admin': False}
dict_values

# Question 32: Count True values in boolean dictionary
dict_values={'is_active': True, 'is_admin': False}
count=0
for i in dict_values.values():
  if i==True:
    count+=1
print(count)

# Question 33: Create a dictionary with complex numbers: {'z1': 3+4j, 'z2': 1+2j}
dict_values={'z1': 3+4j, 'z2': 1+2j}
dict_values

# Question 34: Find magnitude of each complex number
dict_values={'z1': 3+4j, 'z2': 1+2j}
for i in dict_values.values():
  print(abs(i))

# Question 35: Create a 4-level nested dictionary
dict_values={'a': {'b': {'c': {'d':{'x':23}}}}}
dict_values

# Question 36: Access deepest value in 4-level nested dictionary
dict_values={'a': {'b': {'c': {'d':{'x':23}}}}}
dict_values['a']['b']['c']['d']['x']

# Question 37: Create a dictionary with range values: {'r1': range(3), 'r2': range(5)}
dict_values={'r1': range(3), 'r2': range(5)}
dict_values

# Question 38: Convert each range to list
dict_values={'r1': range(3), 'r2': range(5)}
for i in dict_values.values():
  print(list(i))

# Question 39: Create a dictionary with generator values
dict_values={'g1': (i for i in range(3)), 'g2': (i for i in range(5))}
dict_values

# Question 40: Convert each generator to list
dict_values={'g1': (i for i in range(3)), 'g2': (i for i in range(5))}
for i in dict_values.values():
  print(list(i))

# Question 41: Create a dictionary with iterator values
dict_values={'it1': iter(range(3)), 'it2': iter(range(5))}
dict_values

# Question 42: Extract all elements from each iterator
dict_values={'it1': iter(range(3)), 'it2': iter(range(5))}
for i in dict_values.values():
  print(list(i))

# Question 43: Create a dictionary with nested lists: {'matrix': [[1, 2], [3, 4]], 'vector': [5, 6, 7]}
dict_values={'matrix': [[1, 2], [3, 4]], 'vector': [5, 6, 7]}
dict_values

# Question 44: Find sum of each nested list
dict_values={'matrix': [[1, 2], [3, 4]], 'vector': [5, 6, 7]}
matrix_sum=sum(dict_values['matrix'][0])+sum(dict_values['matrix'][1])
vector_sum=sum(dict_values['vector'])
print(matrix_sum)
print(vector_sum)

dict_values = {'matrix': [[1, 2], [3, 4]],'vector': [5, 6, 7]}
matrix_total = 0
vector_total = 0
a = dict_values['matrix']
b = dict_values['vector']
for i in a:
    for j in i:
        matrix_total = matrix_total +j
for i in b:
  vector_total = vector_total + i
print(vector_total)
print(matrix_total)

# Question 45: Create a dictionary with nested dictionaries: {'config': {'db': {'host': 'localhost', 'port': 5432}}}
dict_values={'config': {'db': {'host': 'localhost', 'port': 5432}}}
dict_values

# Question 46: Access database port from nested configuration
dict_values={'config': {'db': {'host': 'localhost', 'port': 5432}}}
dict_values['config']['db']['port']

# Question 47: Create a dictionary with nested tuples: {'points': ((1, 2), (3, 4)), 'rgb': ((255, 0, 0), (0, 255, 0))}
dict_values={'points': ((1, 2), (3, 4)), 'rgb': ((255, 0, 0), (0, 255, 0))}
dict_values

# Question 48: Extract first point coordinates
dict_values={'points': ((1, 2), (3, 4)), 'rgb': ((255, 0, 0), (0, 255, 0))}
dict_values['points'][0]

# Question 49: Create a dictionary with nested sets: {'groups': {{1, 2, 3}, {4, 5, 6}}, 'categories': {{'a', 'b'}, {'c', 'd'}}}
dict_values={'groups': ({1, 2, 3}, {4, 5, 6}), 'categories': ({'a', 'b'}, {'c', 'd'})}
dict_values

# Question 50: Find union of all nested sets
dict_values={'groups': ({1, 2, 3}, {4, 5, 6}), 'categories': ({'a', 'b'}, {'c', 'd'})}
a=dict_values['groups'][0].union(dict_values['groups'][1])
b=dict_values['categories'][0].union(dict_values['categories'][1])
print(a,b)