# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RuUl2ZdqdXsITgrbByRjsJ80OsEW4QMd
"""

# # Question 1: Create a list of first 10 square numbers
square_numbres=[]
for i in range(1,11):
  # print(i**2)
  square_numbres.append(i**2)
print(square_numbres)

# # Question 2: Find the sum of all even numbers in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum_of_even=0
for i in numbers:
  if i%2==0:
    sum_of_even=sum_of_even+i
print(sum_of_even)

# Question 3: Remove duplicates from [1, 2, 2, 3, 4, 4, 5, 6, 6, 7]
numbers=[1, 2, 2, 3, 4, 4, 5, 6, 6, 7]
result=set(numbers)
print(result)

# Question 4: Sort the list [64, 34, 25, 12, 22, 11, 90] in descending order
numbers=[64, 34, 25, 12, 22, 11, 90]
result=sorted(numbers ,reverse=True)
print(result)

# Question 5: Find the average of numbers in [15, 23, 31, 42, 56, 78, 91]
numbers=[15, 23, 31, 42, 56, 78, 91]
ave_of_numbers=0
for i in numbers:
  ave_of_numbers=ave_of_numbers+i
print(ave_of_numbers/len(numbers))

# Question 6: Create a list of first 15 Fibonacci numbers
a=0
b=1
for i in range(0,15):
  number=(a)
  c=a+b
  a=b
  b=c
  print(number)

# Question 7: Find the second largest number in [45, 67, 23, 89, 12, 34, 78]
numbers=[45, 67, 23, 89, 12, 34, 78]
numbers.sort()
print(numbers[-2])

# Question 8: Reverse the list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers.reverse()
print(numbers)

# Question 9: Count how many times 5 appears in [1, 5, 2, 5, 3, 5, 4, 5, 6]
numbers=[1, 5, 2, 5, 3, 5, 4, 5, 6]
count=0
for i in numbers:
  if i==5:
    count=count+1
print(count)

# Question 10: Create a list of prime numbers between 1 and 50
prime_numbers=[]
for i in range(1,51):
  count=0
  if i>1:
    for j in range(2,i):
      if i%j==0:
        count=count+1
    if count==0:
      prime_numbers.append(i)
print(prime_numbers)

# Question 11: Flatten nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result=[]
for i in lst:
  for j in i:
    result.append(j)
print(result)

# Question 12: Find common elements between [1, 2, 3, 4, 5] and [4, 5, 6, 7, 8]
lst1=[1, 2, 3, 4, 5]
lst2=[4, 5, 6, 7, 8]
result=[]
for i in lst1:
  for j in lst2:
    if i==j:
      result.append(i)
print(result)

# Question 13: Create a list of lists: [[1, 2], [3, 4], [5, 6]]
lst=[[1, 2], [3, 4], [5, 6]]
print(lst)

# Question 14: Find the sum of each sublist in [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
sub_lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
sum_of_elements=0
for i in sub_lst:
  for j in i:
    sum_of_elements=sum_of_elements+j
print(sum_of_elements)

# Question 15: Transpose the matrix [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result=[[lst[j][i] for j in range(len(lst))] for i in range(len(lst[0]))]
print(result)

# Question 16: Find the maximum value in each sublist of [[1, 5, 3], [9, 2, 7], [4, 8, 6]]
lst=[[1, 5, 3], [9, 2, 7], [4, 8, 6]]
max_value=0
for i in lst:
  for j in i:
    if j>max_value:
      max_value=j
print(max_value)

# Question 17: Create a 3D list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
lst=[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(lst)

# Question 18: Find the sum of all elements in 3D list [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
lst=[[1, 2], [3, 4]]
sum_of_elements=0
for i in lst:
  for j in i:
    sum_of_elements=sum_of_elements+j
print(sum_of_elements)

# Question 19: Extract all even numbers from nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for i in lst:
  for j in i:
    if j%2==0:
      print(j)

# Question 20: Create a list of mixed data types: [1, "hello", 3.14, True, [1, 2, 3]]
lst=[1, "hello", 3.14, True, [1, 2, 3]]
print(lst)

# Question 21: Find the length of each string in ["apple", "banana", "cherry", "date"]
lst=["apple", "banana", "cherry", "date"]
for i in lst:
  print(len(i))

# Question 22: Create a list of tuples: [(1, 'a'), (2, 'b'), (3, 'c')]
lst=[(1, 'a'), (2, 'b'), (3, 'c')]
print(lst)

# Question 23: Extract first element from each tuple in [(1, 'a'), (2, 'b'), (3, 'c')]
lst=[(1, 'a'), (2, 'b'), (3, 'c')]
for i in lst:
  print(i[0])

# Question 24: Create a list of dictionaries: [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]
lst=[{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]
print(lst)

# Question 25: Extract all 'name' values from list of dictionaries
lst=[{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]
for i in lst:
  print(i['name'])

# Question 26: Find the person with maximum age in list of dictionaries
lst=[{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]
max_age=0
for i in lst:
  if i['age']>max_age:
    max_age=i['age']
print(max_age)

# Question 27: Create a 4D list: [[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]
lst=[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]
print(lst)

# Question 28: Find the maximum value in 4D list
lst=[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]
max_value=0
for i in lst:
  for j in i:
    for k in j:
      for l in k:
        if l>max_value:
          max_value=l
print(max_value)

# Question 29: Create a list of sets: [{1, 2, 3}, {4, 5, 6}, {7, 8, 9}]
lst=[{1, 2, 3}, {4, 5, 6}, {7, 8, 9}]
print(lst)

# Question 30: Find the union of all sets in list of sets
lst=[{1, 2, 3}, {4, 5, 6}, {7, 8, 9}]
union_set=set()
for i in lst:
  union_set=union_set.union(i)
print(union_set)

# Question 31: Create a list of complex numbers: [1+2j, 3+4j, 5+6j]
lst=[1+2j, 3+4j, 5+6j]
print(lst)

# Question 32: Find the magnitude of each complex number in list
lst=[1+2j, 3+4j, 5+6j]
for i in lst:
  print(abs(i))

# Question 33: Create a nested list with different levels: [1, [2, 3], [4, [5, 6]], 7]
lst=[1, [2, 3], [4, [5, 6]], 7]
print(lst)

# Question 34: Count the depth of nesting in [1, [2, 3], [4, [5, 6]], 7]
lst=[1, [2, 3], [4, [5, 6]], 7]
count=0
for i in lst:
  if type(i)==list:
    count=count+1
print(count)

# Question 35: Create a list of functions: [len, str, int, float]
lst=[len, str, int, float]
print(lst)

# Question 36: Apply each function in list to string "123"
lst=[len, str, int, float]
for i in lst:
  print(i("123"))

# Question 37: Create a list of lambda functions: [lambda x: x*2, lambda x: x**2, lambda x: x+1]
lst=[lambda x: x*2, lambda x: x**2, lambda x: x+1]
print(lst)

# Question 38: Apply each lambda function to 5
lst=[lambda x: x*2, lambda x: x**2, lambda x: x+1]
for i in lst:
  print(i(5))

# Question 39: Create a list of classes: [list, dict, set, tuple]
lst=[list, dict, set, tuple]
print(lst)

# Question 40: Create instances of each class in list
lst=[list, dict, set, tuple]
for i in lst:
  print(i())

# Question 41: Create a list of None values: [None, None, None, None]
lst=[None, None, None, None]
print(lst)

# Question 42: Replace all None values with 0 in list
lst=[None, None, None, None]
for i in range(len(lst)):
  lst[i]=0
print(lst)

# Question 43: Create a list of boolean values: [True, False, True, False]
lst=[True, False, True, False]
print(lst)

# Question 44: Count True values in boolean list
lst=[True, False, True, False]
count=0
for i in lst:
  if i==True:
    count=count+1
print(count)

# Question 45: Create a list of ranges: [range(3), range(5), range(2)]
lst=[range(3), range(5), range(2)]
print(lst)

# Question 46: Convert each range to list
lst=[range(3), range(5), range(2)]
for i in lst:
  print(list(i))

# Question 47: Create a list of generators: [(x for x in range(3)), (x for x in range(5))]
lst=[(x for x in range(3)), (x for x in range(5))]
print(lst)

# Question 48: Convert each generator to list
lst=[(x for x in range(3)), (x for x in range(5))]
for i in lst:
  print(list(i))

# Question 49: Create a list of iterators: [iter([1, 2, 3]), iter([4, 5, 6])]
lst=[iter([1, 2, 3]), iter([4, 5, 6])]
print(lst)

# Question 50: Extract all elements from each iterator
lst=[iter([1, 2, 3]), iter([4, 5, 6])]
for i in lst:
  for j in i:
    print(j)
# print(lst)