# -*- coding: utf-8 -*-
"""None_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ae9g3edVoRAIQUoNOjU1GD-gyW9f8D31
"""

# Question 1: Create a variable and assign None to it
value=None
print(value)

# Question 2: Check if None equals None
if None==None:
    print("None equals None")
else:
  print("false")

# Question 3: Check if None is None
if None is None:
    print("None is None")
else:
  print("false")

# Question 4: Check if 0 is None
if 0 is None:
    print("0 is None")
else:
  print("false")

# Question 5: Check if empty string is None
if "" is None:
    print("empty string is None")

# Question 6: Check if False is None
if False is None:
    print("true")
else:
  print("false")

# Question 7: Check if empty list is None
if [] is None:
    print("true")
else:
  print("false")

# Question 8: Check if empty dictionary is None
if {} is None:
    print("true")
else:
  print("false")

# Question 9: Check if empty tuple is None
if () is None:
    print("true")
else:
  print("false")

# Question 10: Check if empty set is None
if set() is None:
    print("true")
else:
  print("false")