# -*- coding: utf-8 -*-
"""Set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghNxI35gSw-98onPyAMxYeik8DczCiFC
"""

# Question 1: Create a set of first 10 natural numbers
natural_numbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
natural_numbers

# Question 2: Add element 11 to set {1, 2, 3, 4, 5}
natural_numbers.add(11)
natural_numbers

# Question 3: Remove element 3 from set {1, 2, 3, 4, 5, 6}
natural_numbers.remove(3)
natural_numbers

# Question 4: Find the intersection of {1, 2, 3, 4, 5} and {4, 5, 6, 7, 8}
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
inter = set1.intersection(set2)
inter

# Question 5: Find the difference between {1, 2, 3, 4, 5} and {4, 5, 6, 7, 8}
difference = set1.difference(set2)
difference

# Question 6: Check if 5 is in set {1, 2, 3, 4, 6, 7, 8}
set_numbers= {1, 2, 3, 4, 6, 7, 8}
5 in set_numbers

# Question 7: Find the length of set {'a', 'b', 'c', 'd', 'e'}
set_numbers = {'a', 'b', 'c', 'd', 'e'}
len(set_numbers)

# Question 8: Create a set of vowels from string "hello world"
string = "hello world"
vowels = {'a', 'e', 'i', 'o', 'u'}
set_numbers = set()
for i in string:
    if i in vowels:
        set_numbers.add(i)
set_numbers

# Question 9: Remove duplicates from list [1, 2, 2, 3, 4, 4, 5, 6, 6, 7] using set
list1 = [1, 2, 2, 3, 4, 4, 5, 6, 6, 7]
list2 = list(set(list1))
list2

# Question 10: Check if {1, 2, 3} is a subset of {1, 2, 3, 4, 5, 6}
set_numbers = {1, 2, 3}
set_number = {1, 2, 3, 4, 5, 6}
set_numbers.issubset(set_number)