# -*- coding: utf-8 -*-
"""Tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWqNzWSOfjX9ki6SeqSdXwyXTSpDnTpr
"""

# Question 1: Create a tuple of first 10 natural numbers
natural_numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(natural_numbers)

# Question 2: Find the length of tuple (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
numbers=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
len(numbers)

# Question 3: Access the 3rd element from tuple ('a', 'b', 'c', 'd', 'e')
tuple = ('a', 'b', 'c', 'd', 'e')
tuple[2]

# Question 4: Find the maximum value in tuple (23, 45, 12, 67, 34, 89, 56)
numbers=(23, 45, 12, 67, 34, 89, 56)
max(numbers)

# Question 5: Count how many times 5 appears in (1, 5, 2, 5, 3, 5, 4, 5, 6)
numbers=(1, 5, 2, 5, 3, 5, 4, 5, 6)
numbers.count(5)

# Question 6: Create a tuple of mixed data types (integer, float, string, boolean)
values = (10, 3.14, "Hello", True)
print(values)

# Question 7: Find the index of element 'python' in ('java', 'python', 'c++', 'javascript')
elements=('java', 'python', 'c++', 'javascript')
elements.index('python')

# Question 8: Check if 25 exists in tuple (10, 20, 30, 40, 50)
numbers=(10, 20, 30, 40, 50)
if 25 in numbers:
  print('25 present in tuple')
else:
  print('25 not present in tuple')

# Question 9: Create a tuple of first 5 even numbers
even_numbers = (2, 4, 6, 8, 10)
print(even_numbers)

# Question 10: Find the average of numbers in tuple (15, 23, 31, 42, 56, 78)
numbers=(15, 23, 31, 42, 56, 78)
average=sum(numbers)/len(numbers)
print(average)